py_library(
    name = "utils",
    srcs = ["math_utils.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "math_utils_test",
    srcs = ["math_utils_test.py"],
    deps = [":utils"],
)